### ISSUE TITLE
[Bug] Magnifier position is wrong when content has margin

### ISSUE THREAD

**Issue by zangzimi** [ReynardFox99/mobile-text-selection#10]
Thanks for making this awesome tool!

When inner content has margins, the selected text is right but the selected rect positions in the magnifier is wrong. And idea how to fix this? It would be great if you can help!

**Comment by zangzimi** [comment]
@ReynardFox99 Hi. Is this fixed or why is this closed?

**Comment by ReynardFox99** [comment]
fixed...i think...



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 1, 2022 21:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ReynardFox99/mobile-text-selection] [Bug] Magnifier position iswrong when content has margin (Issue #10)




 
@ReynardFox99 Hi. Is this fixed or why is this closed?
